name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: "gradle"

      - name: Generate assets
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: runData -Pdev=false

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build -Pdev=false

      - name: Extract mod version and check tag exists
        id: version
        run: |
          MOD_VERSION=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "mod_version=$MOD_VERSION" >> $GITHUB_OUTPUT

          TAG_EXISTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${MOD_VERSION} | jq -r .ref)

          if [ "$TAG_EXISTS" != "null" ]; then
            echo "Tag $MOD_VERSION already exists. Skipping release."
            echo "skip_release=true" >> $GITHUB_OUTPUT
          else
            echo "skip_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release if not already published
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && steps.version.outputs.skip_release == 'false'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.version.outputs.mod_version }}
          prerelease: true
          title: "EntityTrackerHUD Build ${{ steps.version.outputs.mod_version }}"
          files: |
            ./build/libs/*.jar
